# Generated by Django 5.1.7 on 2025-03-31 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0003_remove_hackathonapplication_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathonslist',
            name='prize',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
    ]
