# Generated by Django 5.1.7 on 2025-03-31 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0005_hackathonslist_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathonslist',
            name='created_by',
        ),
    ]
