# Generated by Django 5.1.7 on 2025-03-31 12:31

import django.db.models.deletion
import hackathons.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathons', '0007_hackathonslist_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathonslist',
            name='created_by',
            field=models.ForeignKey(default=hackathons.models.get_default_user, on_delete=django.db.models.deletion.CASCADE, related_name='created_hackathons', to=settings.AUTH_USER_MODEL),
        ),
    ]
